---
title: "R Notebook"
output: html_notebook
---


```{r}
library(reticulate)
#use_condaenv("dsfs2", required = TRUE)
#install.packages("here")
library(here)
library(readr)
library(tidyverse)
library(rsample)
library(ISLR)
library(caret)
library(scales)
library(pROC)
library(randomForest)
library(gbm)
library(NeuralNetTools)
library(nnet)
library()

```
```{r}
ruta <- here("main", "data", "processed", "imdb_with_sentiment.csv")

data <- read.csv(ruta, sep = ",")

data <- data %>%
  rename(Duration = Duration..min.) %>%
  mutate(Votes = as.numeric(gsub(",", "", Votes)),
         Review.Count = as.numeric(gsub(",", "", Review.Count))) %>%
  mutate(across(c(Duration, Review.Count, Votes, Rating, Metascore), ~ rescale(.x, to = c(0, 1))))

# data$Votes %>% as.numeric(gsub(",", "", data$Votes))


data %>% glimpse()
```
```{r}
data <- data %>%
  select(-c(Title, Year, Director, Genre, Cast, Description, Review.Title, Review, metascore_missing, reviews_tokenizadas, Duration, compound))

data %>% summary()
```
```{r}
data %>% pull(sentiment) %>% table()

Sentiment_pos <- data %>%
  filter(sentiment == 1) %>%
  sample_n(1831)

Sentiment_neg <- data %>% filter(sentiment == -1)

data <- bind_rows(Sentiment_pos, Sentiment_neg)
data %>% pull(sentiment) %>% table()
```
```{r}
data <- data %>%
  mutate(sentiment = ifelse(sentiment == 1, 1, 0)) %>%
  mutate(sentiment = as.factor(sentiment))
```
```{r}
data %>%
  pivot_longer(cols = -sentiment,
               names_to = "Variable", values_to = "Value") %>%
  ggplot() +
  aes(x = as.factor(sentiment), y = Value, color = as.factor(sentiment)) +
  geom_violin(trim = TRUE) +
  facet_wrap(vars(Variable), scales = "free") +
  theme_minimal()
```
```{r}
set.seed(123)
dsplit <- data %>% initial_split(prop = 0.8, strata = sentiment)
dtrain <- dsplit %>% training()
dtest <- dsplit %>% testing()
```
```{r}
dtrain$sentiment %>% table()
```
```{r}
model_glm <- dtrain %>%
  glm(sentiment ~ ., data = ., family = "binomial")

model_glm %>% summary()
# Obtener un p-valor menor que 0.05 nos indica que la variable rating tiene un efecto significativo en el sentimiento,
# es decir, a medida que aumenta el resto de variables significativas, aumenta la probabilidad de que el sentimiento sea positivo
# entre las variables más signigicativas para el modelo de claseificación binominal tenemos, Rating, Votes y Review.Count
```
```{r}
dtest <- dtest %>%
  mutate(sentiment = factor(sentiment, levels = c("0", "1")))

pred_glm <- model_glm %>% predict(newdata = dtest, type = "response")

pred_class_glm <- ifelse(pred > 0.5, "1", "0") %>%
  factor(levels = levels(dtest$sentiment))
```
```{r}
pred_glm <- confusionMatrix(data = pred_class_glm,
                          reference = dtest$sentiment,
                          mode = "everything",
                          positive = "1")
pred_glm

# En cuanto a la matriz de confusión del modelo binominal podemos decir que:
# El modelo tiene una tasa de 241 verderos positivos, respecto a los 201 de verdaderos negativos
# Si hablamos de los errores más críticos hay que comentar que la tasa de falsos positivos resulta en un valor
# de 166 y falsos negativos de un valor 126, ambos valores son tasas altas de errores, debido a que son los erores
# más graves que se puede obtener

# Comenzaremos a interpretar cada una de las métricas derivadas de la matriz de confusión:

# Accuracy - mide la proporción de predicciones correctas del modelo, en este caso obtenemos un valor entorno
# al 60%, lo que nos indica que se trata de un modelo aceptable bajo, el modelo es mejor que lanzar una moneda al aire

# En cuanto a la métrica de sensibilidad, con un valor de 65%, indica la capacidad del modelo para identificar
# a los verdaderos positivos.

# Para la métrica de especificidad, con un valor de 54%, mide la capacidad del modelo para identificar a los
# verdaderos negativos, con respecto a la métrica anterior indica que nuestro modelo de clasificación binaria
# predice mejor aquellos casos verdaderos positivos.

# Por úñtimo, para la métrica de f1, la cual combina en un único valor dos aspectos clave del modelo, la precisión
# y la sensibilidad, esta métrica se calcula como la media armónica entre estas dos anteriores.
# Para este caso, disponemos de una baja precisión y un alto recall, lo que nos hace indicar que el modelo detecta
# bien las clases, pero incluye muchos falsos positivos.

```
```{r}
pred_glm %>%
        roc(response = dtest$sentiment, plot = TRUE, auc = TRUE)

# calculando el auc, la cual mide la capacidad del modelo para discriminar entre las clases, hemos obtenido una valor
# de 64%, lo quie nos hace indicar que el modelo tiene un desempeño bajo, sin embargo, se trata de un buen punto
# partida para comenzar desde el modelo de clasifiacción binaria.

# Realizando la curva de roc podemos observar
```
```{r}


p <- ncol(dtrain) - 1
B <- 1000
model_Bag <- dtrain %>%
        randomForest(sentiment ~ ., data = ., ntree = B, mtry = p, importance = TRUE)

model_Bag

model_RF <- dtrain %>%
        randomForest(sentiment ~ ., data = ., ntree = B, mtry = sqrt(p), importance = TRUE)

model_RF
#model %>% varImpPlot()

```
```{r}
model_Bag %>% varImpPlot()
model_RF %>%  varImpPlot()
```
```{r}
m <- dtrain %>%
  train(sentiment ~ ., data = ., method = "rf", metric = "Accuracy",
        trControl = trainControl(method = "cv", number = 10),
        tuneGrid = expand.grid(mtry = 1:p),
        ntree = B)

m %>% plot()
m$bestTune$mtry
```
```{r}
model_randomF <- dtrain %>%
  randomForest(sentiment ~ ., data = ., mtry = m$bestTune$mtry, ntree = B, importance = TRUE)

model_randomF
```
```{r}
pred_randomF <- model_randomF %>% predict(dtest, type = "class")
pred_randomF %>% confusionMatrix(reference = dtest$sentiment, mode = "everything", positive = "1")
```
```{r}
prob_randomF <- model_randomF %>% predict(dtest, type = "prob")
prob_randomF[,2] %>% roc(response = dtest$sentiment, plot = TRUE, auc = TRUE)
mean(prob_randomF != dtest$sentiment)
```
```{r}
B <- 1000
lambda <- dtrain %>%
  train(sentiment ~ .,data = .,distribution = "bernoulli",
        method = "gbm",metric = "Accuracy",
        trControl = trainControl(method = "cv", number = 10),
        tuneGrid = expand.grid(n.trees = B, interaction.depth = 2,
                               shrinkage = c(0.001,0.01,0.1),n.minobsinnode = 10),verbose = FALSE)
lambda %>% plot()
lambda$bestTune$shrinkage
```
```{r}
model_gbm <- dtrain %>%
  mutate(
    sentiment = ifelse(sentiment == "1", 1, 0)
  ) %>%
        gbm(sentiment ~ ., data = ., n.trees = B,
            interaction.depth = 2 , shrinkage = lambda$bestTune$shrinkage,
            n.minobsinnode = 10, verbose = FALSE,
            distribution = "bernoulli")

model_gbm %>% summary()
```
```{r}
pred_gbm <- model_gbm %>% predict(dtest, type = "response")
pred_new_gbm <- factor(ifelse(pred>0.5, "1", "0"))
pred_new_gbm %>% confusionMatrix(reference = dtest$sentiment,
                             mode = "everything", positive = "1")
```
```{r}
pred_gbm %>% roc(response = dtest$sentiment, plot = TRUE, auc = TRUE)
mean(pred_new_gbm != dtest$sentiment)
```
```{r}
model_nn <- dtrain %>%
        train(sentiment ~ ., data = ., method = "nnet", metric = "Accuracy",
              trControl = trainControl(method = "cv", number = 10),
              tuneGrid = expand.grid(size = 1:p, decay = c(0.01, 0.1, 0.5, 1)),
              linout = FALSE, verbose = FALSE)

model_nn$bestTune
```
```{r}
m_nnet <- dtrain %>%
        nnet(sentiment ~ ., data = ., size = model_nn$bestTune$size,
             decay = model_nn$bestTune$decay, linout = FALSE)

m_nnet %>% plotnet()
```
```{r}
pred_nnet <- m_nnet %>% predict(dtest, type = "class") %>% as.factor()
pred_nnet %>% confusionMatrix(reference = dtest$sentiment, mode = "everything", positive = "1")
prob_nnet <- m_nnet %>% predict(dtest)
```
```{r}
prob_nnet[,1] %>% roc(response = dtest$sentiment, plot = TRUE, auc = TRUE)
mean(pred_nnet != dtest$sentiment)
```
```{r}
cm_glm <- confusionMatrix(data = pred_class_glm, reference = dtest$sentiment, positive = "1")
cm_RF <- confusionMatrix(data = pred_randomF, reference = dtest$sentiment, positive = "1")
cm_gbm <- confusionMatrix(data = pred_new_gbm, reference = dtest$sentiment, positive = "1")
cm_nnet <- confusionMatrix(data = pred_nnet, reference = dtest$sentiment, positive = "1")

best_model_classification <- data.frame(
        model = c("Regresion Logistica", "Random Forest", "Gradient Boosting", "Redes Neuronales"),
        Precision = c(cm_glm$byClass['Precision'], cm_RF$byClass['Precision'], cm_gbm$byClass['Precision'], cm_nnet$byClass['Precision']),
        Recall = c(cm_glm$byClass['Recall'], cm_RF$byClass['Recall'], cm_gbm$byClass['Recall'], cm_nnet$byClass['Recall']),
        Specificity = c(cm_glm$byClass['Specificity'], cm_RF$byClass['Specificity'], cm_gbm$byClass['Specificity'], cm_nnet$byClass['Specificity'])
)



```
```{r}
get_metrics <- function(var, pred, model) {
  cm <- confusionMatrix(pred, var)

  data.frame(
          Model = model,
          Precision = cm$byClass['Precision'],
          Recall = cm$byClass['Recall'],
          Specificity = cm$byClass['Specificity']
  )
}

metrics_glm <- get_metrics(dtest$sentiment, pred_glm, "LogReg")
metrics_RF <- get_metrics(dtest$sentiment, pred_randomF, "RandomForest")
metrics_gbm <- get_metrics(dtest$sentiment, pred_new_gbm, "GradientBoosting")
metrics_nnet <- get_metrics(dtest$sentiment, pred_nnet, "NNet")

all_metrics <- rbind(metrics_glm, metrics_RF, metrics_gbm, metrics_nnet)
rownames(all_metrics) <- NULL
print(all_metrics)

```

